#!/usr/bin/env python
from ATATools import ata_sources
from datetime import datetime, timezone, timedelta
import pytz
import argparse

def main():
    parser = argparse.ArgumentParser(description=
            '''Display information about a source, including current
            position, rise and set times, etc...''')
    parser.add_argument('source', nargs='?',
            help='source name in ATA database')

    parser.add_argument('--radec', nargs=2,
            required=False, type=float,
            help='RA [decimal hours], Dec [decimal degrees] pair')

    args = parser.parse_args()

    if (args.source is not None) and (args.radec is not None):
        raise RuntimeError('Provide only "source" or "RA/Dec" pair')

    dt = datetime.now(pytz.timezone('US/PACIFIC'))

    if args.source:
        output_str = ata_sources.check_source_str(dt, sourcename=args.source)
    elif args.radec:
        output_str = ata_sources.check_source_str(dt, radec=args.radec)

    # Now let's print
    print(output_str)

if __name__ == "__main__":
    main()
