#!/usr/bin/env python
from ATATools.ata_if import tune_if
from ATATools import logger_defaults

import numpy as np
import argparse
import logging
import sys,os

ALL_LOS = ['a', 'b', 'c', 'd']
ALL_POLS = ['x', 'y']

def main():
    parser = argparse.ArgumentParser(description=
             "Tune attemplifiers for given antennas, polarization, and LO")
    parser.add_argument('ants', nargs="+",
            help="Antenna names")
    parser.add_argument('-l', '--lo', nargs="+",
            help="LO names", default=ALL_LOS)
    parser.add_argument('-p', '--pol', nargs="+",
            help="Polarizations", default=ALL_POLS)
    parser.add_argument('-v', '--verbose', action='count', default=0,
            help="Verbosity")

    args = parser.parse_args()

    if args.verbose == 1:
        logger = logger_defaults.getProgramLogger(
                os.path.basename(sys.argv[0]),
                loglevel=logging.INFO)
    elif args.verbose > 1:
        logger = logger_defaults.getProgramLogger(
                os.path.basename(sys.argv[0]),
                loglevel=logging.DEBUG)

    ant_list = np.array(args.ants)
    los      = np.array(args.lo)
    pols     = np.array(args.pol)

    for lo in los:
        if lo not in ALL_LOS:
            raise RuntimeError("LO: %s not in default LO list" %lo)
    for pol in pols:
        if pol not in ALL_POLS:
            raise RuntimeError("Pol: %s not in default pol list"%pol)

    tune_if(ant_list, los, pols)

if __name__ == "__main__":
    main()
