#!/usr/bin/env python
import tkinter as tk
from ATATools.ata_obs_plot_app import ObsPlotApp

if __name__ == "__main__":
    root = tk.Tk()
    root.geometry("1550x900")  # Set the window size to 1450x900 pixels
    app = ObsPlotApp(root)
    root.mainloop()
