#!/usr/bin/env python
from ATATools import ata_sources
from ATATools import logger_defaults

import numpy as np
import argparse
import logging
import sys,os


def main():
    parser = argparse.ArgumentParser(description=
            "List ata source catalog")
    parser.add_argument('source', type=str,
            help="source catalog owner")
    parser.add_argument('coords', type=float, nargs="*",
            help="RA [decimal hours] and Dec [decimal degrees]")
    parser.add_argument('-o', '--owner', default=None,
            required=True,
            help="source catalog owner")
    parser.add_argument('-c', '--category', default=None,
            required=True,
            help="source catalog category")
    parser.add_argument('-d', '--delete', action="store_true",
            help="Delete source from catalog")

    args = parser.parse_args()

    # Deleting entry from database
    if args.delete:
        ata_sources.delete_catalog_entry(owner=args.owner,
                category=args.category, source=args.source)

    # Adding entry to database
    else:
        if len(args.coords) != 2:
            raise RuntimeError("Please provide RA/dec pairs")

        ata_sources.add_catalog_entry(owner=args.owner,
                category=args.category, source=args.source,
                ra=args.coords[0], dec=args.coords[1])

if __name__ == "__main__":
    main()
