#!/bin/bash

echo ""
echo "                     === ATA Commands Menu ==="
echo ""
echo " + atahint        - useful hint(s)."
echo " + setalarm       - send out an email stating you are using the array."
echo " + ataasciistatus - get the pointing and status of all the dishes."
echo " + atacheck       - get the rise/set times and location of an object";
echo " + getdetpams     - get the PAM dB setting and detector values for a feed"
echo " + weather        - get the weather station output"
echo " + antgroups      - list the antenna groups"
echo " + antreserve     - move ants from groups"
echo " + pointshift     - point the dishes in group \"bfa\" and optionally offset"
echo " + getskyfreq     - get the frequency of LOA"
echo " + setskyfreq     - set the frequency of LOA"
echo " + park           - park all the dishes"
echo " + jackwatch      - print out pointing status every 10 seconds"
echo " + sefd2db        - store an SEFD in the database"
echo " + obs2db         - record an observation in the database"
echo " + obsgetid       - get the id of the most recent observation id."
echo " + rfassignant    - assign an antenna pol to an RF switch input, store in db.";
echo " + rfgethookup    - get the RF switch port and antenna pol is hooked to. Queries db.";
echo " + rfswitchant    - actually switch the RF switch on an antenna pol input.";

echo

fortune
ddate
echo
