install:
	cp antgroups /usr/local/bin 
	cp ataasciistatus /usr/local/bin
	cp atacheck /usr/local/bin
	cp atamenu /usr/local/bin  
	cp getdetpams /usr/local/bin  
	cp pointshift /usr/local/bin
	cp weather /usr/local/bin
	cp atamenu /usr/local/bin
	cp antgroups /usr/local/bin
	cp antreserve /usr/local/bin
	cp pointshift /usr/local/bin
	cp atahint /usr/local/bin
	cp atahint.txt /usr/local/bin
	cp setalarm /usr/local/bin
	cp getskyfreq /usr/local/bin

