#!/usr/bin/env bash

#python=/home/sonata/miniconda3/envs/rfsoc8bit/bin/python
#basedir=/home/sonata/src/ata_snap

python=/opt/mnt/miniconda3/envs/testrfsoc2/bin/python
basedir=/home/sonata/wfarah/ata_snap

${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc1.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc2.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc3.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc4.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc5.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc6.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc7.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc8.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc9.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc10.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc11.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc12.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc13.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc14.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc15.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc16.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc17.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc18.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc19.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc20.hcro.org &
${python} ${basedir}/sw/ata_snap/scripts/rfsoc_program_clocks.py --lmkconf ${basedir}/sw/config/Jack_CLK1REF_10M_LMK_PL_OUT_50M_adc_on.txt --lmxconf ${basedir}/sw/config/Jack_LMX_50_IN_256_OUT.txt --siconf ${basedir}/sw/config/Si5341-RevD-ATA001-156_25M-041521-Registers.txt rfsoc21.hcro.org &
wait
