#!/usr/bin/expect
set sonata_password [exec gpg -d $env(HOME)/TerminatorObservationConsole/.sonata.password.gpg 2>/dev/null]

spawn ssh sonata@dsp-control.hcro.org

expect "password"
send "$sonata_password\r";

expect "sonata@dsp-control"
send -- "cd ~/dev/delay_engine/\r";
send -- "clear; echo \"Start the LOb delay engine here: 'python delay_engine.py -telinfo /opt/mnt/share/telinfo_ata.toml -lo b -fixed /opt/mnt/share/delays_b.txt -phases /opt/mnt/share/phases_b.txt'\"\r"

interact

#EOF
